# -*- coding: utf-8 -*-
"""longlat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qkheWE3RU1TudYfeIjMp0iDr9VsDWKW
"""

import streamlit as st
import pandas as pd
import pydeck as pdk

st.title("Latitude and Longitude Map")

st.write("Enter a latitude and longitude to display the location on the map.")

latitude = st.number_input(
    "Enter latitude:",
    min_value=-90.0,
    max_value=90.0,
    value=39.2904,
    format="%.6f"
)

longitude = st.number_input(
    "Enter longitude:",
    min_value=-180.0,
    max_value=180.0,
    value=-76.6122,
    format="%.6f"
)

if st.button("Show Location"):
    location_data = pd.DataFrame(
        {
            "lat": [latitude],
            "lon": [longitude]
        }
    )

    st.success(f"Showing location: latitude = {latitude}, longitude = {longitude}")

    view_state = pdk.ViewState(
        latitude=latitude,
        longitude=longitude,
        zoom=10,
        pitch=0
    )

    layer = pdk.Layer(
        "ScatterplotLayer",
        data=location_data,
        get_position='[lon, lat]',
        get_radius=1000,
        get_fill_color='[255, 0, 0, 180]',
        pickable=True
    )

    deck = pdk.Deck(
        initial_view_state=view_state,
        layers=[layer],
        tooltip={"text": "Latitude: {lat}\nLongitude: {lon}"}
    )

    st.pydeck_chart(deck)